services:
  db:
    image: postgres:16-alpine
    container_name: furgonetascamper-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: camper
      POSTGRES_PASSWORD: frank1camper2
      POSTGRES_DB: npm install prisma --save-dev

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: